core_app/app.py
from core_app.blueprint import bp
from core_app.config import CustomConfigParser
from core_app.database import SqlHelper, db
from flask import Flask
from flask_session import Session
from redis import Redis
import os

def create_app(*args, **kwargs):
	"""Flask application factory function"""

	# initialise a Flask application
	app = Flask(__name__)

	# load the Flask config referred to in the env var
	if (CustomConfigParser.DEFAULT_SETTINGS_ENV_VAR not in os.environ):
		raise RuntimeError("Please export the {} environment variable".format(CustomConfigParser.DEFAULT_SETTINGS_ENV_VAR))

	app.config.from_envvar(CustomConfigParser.DEFAULT_SETTINGS_ENV_VAR)

	# these two config properties allow db (imported above) to connect to our database throughout the app
	app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
	app.config['SQLALCHEMY_DATABASE_URI'] = SqlHelper.build_conn_str()

	# start a session with Redis as the back-end
	session_redis = Redis.from_url(os.environ["SESSION_REDIS_URL"])
	app.config.update(
		SESSION_REDIS=session_redis
	)

	# register the application blueprints
	app.register_blueprint(bp)

	# init the database on the app
	db.init_app(app)

	# init the session on the app
	sess = Session()
	sess.init_app(app)

	return app

core_app/blueprint.py
import os, dateutil.parser, base64, json
from copy import copy
from flask import current_app, Blueprint, jsonify, request, render_template, url_for, redirect, session
from celery import chain
from core_app.tasks import add, subtract, do_save_customer
from core_app.dao import CustomerDao, UserDao
from core_app.database import session_scope
from core_app.exception import LoginException, UserRegisterException
from core_app.helper import SecurityHelper
from core_app.schema import CustomerSchema
from math import sqrt
from werkzeug.security import generate_password_hash, check_password_hash

# new Blueprint
bp = Blueprint('default', __name__)

@bp.route('/', methods=['GET'], strict_slashes=False)
def home():
	"""Return the site's home page"""
	return render_template('default.html', title='Home')

@bp.route('/customer', methods=['GET'], strict_slashes=False, defaults={"id":-1})
@bp.route('/customer/<int:id>', methods=['GET'], strict_slashes=False)
@SecurityHelper.auth_required
def update_customer(id):
	"""Return the customer update page"""

	customer = None

	if id > -1:

		# start a new session with the database
		with session_scope() as db_session:

			# new instance of our customer dao
			dao = CustomerDao(db_session)
			
			# try to get the customer with the supplied id
			db_customer = dao.get_one_by_id(id)

			if db_customer is not None:
				customer = copy(db_customer)

	# render the update
	return render_template('update-customer.html', title='Update Customer', customer=customer)

@bp.route('/customers', methods=['GET'], strict_slashes=False)
@SecurityHelper.auth_required
def list_customers():
	"""Return the list of customers"""
	return render_template('customer-list.html', title='Customer List')

@bp.route('/login', methods=['POST'], strict_slashes=False)
def login():

	"""
		Select the user from the record matching the posted username
		Compare the posted password to the stored hash
	"""

	# get the form as a dict
	submission = request.form.to_dict(flat=True)

	# raise errors if vital keys are missing
	SecurityHelper.raise_for_login_keys(submission.keys())
			
	# start a database transaction
	with session_scope() as db_session:

		# user our dao to get the user by username
		dao = UserDao(db_session)
		user = dao.get_one_by_username(submission["username"])

		if user is not None:

			# does the supplied password match the hashed password?
			if user.password_matches(submission["password"]):

				# add the user to the session
				session[current_app.config["USER_SESSION_KEY"]] = user.username

				# does the session contain a redirect_url?
				if current_app.config["LOGIN_REDIRECT_SESSION_KEY"] in session.keys():

					# pull the redirect_url from the session and store it in a var
					redirect_url = session[current_app.config["LOGIN_REDIRECT_SESSION_KEY"]]

					# delete the redirect_url from session
					del session[current_app.config["LOGIN_REDIRECT_SESSION_KEY"]]
				else:
					redirect_url = "/"

				# redirect the user to the ur;l
				return redirect(redirect_url)
			else:
				raise LoginException("Invalid password")
		else:
			raise LoginException("User not recognised")

@bp.route('/logout', methods=['POST', 'GET'], strict_slashes=False)
@SecurityHelper.auth_required
def logout():
	"""Remove the user from the session and redirect to login"""
	if current_app.config["USER_SESSION_KEY"] in session.keys():
		del session[current_app.config["USER_SESSION_KEY"]]
		return redirect(current_app.config["LOGIN_URI"])
	else:
		raise KeyError("No user in session")

@bp.route('/login', methods=['GET'], strict_slashes=False)
def show_login():
	"""Return the login page"""
	return render_template('login.html', title='Log In')

@bp.route('/register', methods=['POST'], strict_slashes=False)
def register():
	"""Register the user"""
	
	# get the form as a dict
	submission = request.form.to_dict(flat=True)

	# raise errors if vital keys are missing
	SecurityHelper.raise_for_login_keys(submission.keys())

	# database transaction
	with session_scope() as db_session:

		# try to load an existing user with this username
		dao = UserDao(db_session)

		# get the user by username
		user = dao.get_one_by_username(submission["username"])

		# no user exists, so register
		if user is None:

			# hash the password
			submission["password"] = generate_password_hash(submission["password"])

			# insert to the databsae
			dao.update(submission)

			# redirect to success
			return redirect(url_for("default.show_success"))

		else:
			raise UserRegisterException("{} is already registered".format(user.username))

@bp.route('/register', methods=['GET'], strict_slashes=False)
def show_register():
	"""Return the register page"""
	return render_template('register.html', title='Register')

@bp.route('/customers', methods=['POST'], strict_slashes=False)
@SecurityHelper.auth_required
def query_all_customers():
	"""Load all customers from the db and return as JSON"""
	with session_scope() as db_session:

		dao = CustomerDao(db_session)
		models = dao.get_all()
		schema = CustomerSchema(many=True)

		return jsonify(data=schema.dump(models))

@bp.route('/save-customer', methods=['POST'], strict_slashes=False)
@SecurityHelper.auth_required
def save_customer():
	"""Save the submitted customer to the database"""

	# get the form as a dict
	submission = request.form.to_dict(flat=True)

	# pass the payload to the Celery task and run it
	do_save_customer.s(submission).apply_async()

	# redirect the user to the success page
	return redirect(url_for('default.show_success'))

@bp.route('/delete-customer/<int:id>', methods=['GET'], strict_slashes=False)
@SecurityHelper.auth_required
def delete_customer(id):
	"""Delete customer with id matching the supplied id

		:param (int) id
	"""
	# wrap this operation in a transaction
	with session_scope() as db_session:

		dao = CustomerDao(db_session)

		dao.delete(id)

	# redirect the user to the success page
	return redirect(url_for('default.show_success'))

@bp.route('/success', methods=['GET'], strict_slashes=False)
def show_success():
	"""Render the success page"""
	return render_template('success.html', title='Success')

@bp.route('/intense', methods=['GET'], strict_slashes=False)
@SecurityHelper.auth_required
def intense():
	"""Carry out CPU intensive calculation (for use with Kubernetes Horizontal Pod Autoscaler test)"""
	x = 0.0001

	for i in range(0,1000000):
		x += sqrt(x)

	return jsonify(output="{} -> that was intense!".format(str(x)))

@bp.route('/celery', methods=['GET'], strict_slashes=False)
@SecurityHelper.auth_required
def celery():
	"""Run the add and subtract tasks in a chain, return the outcome in an html template"""

	# construct and run the chain
	result = chain(
		add.s(2,3),
		subtract.s(4)
	)()

	# wait for the result
	result = result.get()

	# render the template passing a title and the outcome as arguments
	return render_template('default.html', title='Celery', output="The chain result is {}".format(result))

@bp.route('/favicon.ico', methods=['GET'], strict_slashes=False)
def favicon():
	return url_for('static', filename='favicon.ico')

core_app/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		{% block head %}
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
		<link rel="stylesheet" href="{{url_for('static', filename='custom.css')}}" />
		{% block custom_head %}{% endblock %}
		<title>{% block title %}{% endblock %}</title>
		{% endblock %}
	</head>
	<body>
		<noscript>
			<div class="alert alert-danger">This website requires JavaScript to function properly.</div>
		</noscript>
		<div class="container">
			{% block nav %}
			<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
				<a class="navbar-brand" href="{{url_for('default.home')}}">
					<h4>Tim Noble</h4>
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item">
							<a class="nav-link" href="/customers">List Customers</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/customer">New Customer</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/celery">Celery</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/intense">Intense</a>
						</li>
					</ul>
				</div>
			</nav>
			{% endblock %}
			<div class="content" id="main-content">
				{% block content %}{% endblock %}
			</div>
			<div id="footer" class="my-3">
				{% block footer %}
				<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
				<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
				<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
				<script src="https://cdnjs.cloudflare.com/ajax/libs/feature.js/1.1.0/feature.min.js" integrity="sha256-sXKlW8vVA7rLANJ+oYJVSMJ6lgZUEkGZxE/MEmkrSVA=" crossorigin="anonymous"></script>
				<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
				<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
				{% block custom_script %}{% endblock %}
				<script>
					if (!feature.classList || !feature.addEventListener) {
						document.getElementById("main-content").innerHTML = "Sorry, your browser is not supported.  This site supports the latest versions of Chrome, Firefox, Safari and Microsoft Edge.  It also supports Microsoft Internet Explorer v10 and above.  Apologies for any inconvenience."
					}
				</script>
				{% endblock %}
			</div>
			<nav class="navbar fixed-bottom navbar-light bg-light">
				<span class="navbar-text mr-sm-2">
					&nbsp;
				</span>
			</nav>
		</div>
	</body>
</html>

core_app/templates/customer-list.html
{% extends "base.html" %}
{% block custom_head %}
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" />
{% endblock %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<h1>{{ self.title() }}</h1>
<div class="card mt-3">
	<div class="card-body">
		<table class="table table-striped table-bordered data-table" id="customers">
			<thead>
				<tr>
					<th>Name</th><th>Postcode</th><th>Country Code</th><th>Updated</th><th>#</th>
				</tr>
			</thead>
		</table>
	</div>
</div>
{% endblock %}
{% block custom_script %}
	<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
	<script src="https://cdn.datatables.net/plug-ins/1.10.20/dataRender/datetime.js"></script>
	<script src="https://cdn.datatables.net/plug-ins/1.10.20/sorting/datetime-moment.js"></script>
	<script src="{{url_for('static', filename='customer-list.js')}}"></script>
{% endblock %}

core_app/templates/default.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="jumbotron">
	<h1 class="display-4">{{ self.title() }}</h1>
	<p class="lead">{{output}}</p>
</div>	
{% endblock %}

core_app/templates/login.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<form id="login-form" method="POST" action="{{ url_for('default.login') }}" class="needs-validation" novalidate>
	<h1>{{title}}</h1>
	<div class="form-group">
		<label for="name">Username</label>
		<input type="text" class="form-control" id="username" name="username" required />
		<div class="invalid-feedback">
			Please enter your username.
		</div>
	</div>
	<div class="form-group">
		<label for="password">Password</label>
		<input type="password" class="form-control" id="password" name="password" required />
		<div class="invalid-feedback">
			Please enter your password.
		</div>
	</div>
	<p />
	<button type="submit" class="btn btn-primary"><span class="oi oi-data-transfer-upload"></span> Submit</button>
</form>
<p>Not registered?  <a href="{{ url_for('default.show_register') }}">Register here</a>.</p>
{% endblock %}
{% block custom_script %}
<script src="{{url_for('static', filename='crud-common.js')}}"></script>
{% endblock %}

core_app/templates/register.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<form id="login-form" method="POST" action="{{ url_for('default.register') }}" class="needs-validation" novalidate>
	<h1>{{ title }}</h1>
	<div class="form-group">
		<label for="name">Email Address</label>
		<input type="text" class="form-control custom-validation" id="username" name="username" required />
		<div class="invalid-feedback">
			Please enter your email address.
		</div>
	</div>
	<div class="form-group">
		<label for="password">Password</label>
		<input type="password" class="form-control custom-validation" id="password" name="password" required />
		<div class="invalid-feedback">
			Your password must be at least 8 characters long and contain 1 lowercase letter, 1 uppercase letter, 1 number and 1 special character from: ! @ # $ % ^ & * ( ) _ +
		</div>
	</div>
	<div class="form-group">
		<label for="confirm-password">Confirm Password</label>
		<input type="password" class="form-control custom-validation" id="confirm-password" name="confirm-password" required />
		<div class="invalid-feedback">
			The passwords do not match
		</div>
	</div>
	<p />
	<button type="submit" class="btn btn-primary"><span class="oi oi-data-transfer-upload"></span> Submit</button>
</form>
{% endblock %}
{% block custom_script %}
<script src="{{url_for('static', filename='crud-common.js')}}"></script>
<script src="{{url_for('static', filename='register.js')}}"></script>
{% endblock %}

core_app/templates/success.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="jumbotron">
	<h1 class="display-4">{{ self.title() }}</h1>
	<p class="lead">{{output}}</p>
</div>	
{% endblock %}

core_app/templates/update-customer.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<form id="customer-form" method="POST" action="{{ url_for('default.save_customer') }}" class="needs-validation" novalidate>
	<h1>Customer{% if customer %}&nbsp;#{{ customer.id }}{% endif %}</h1>
	{% if customer %}
		<input type="hidden" name="id" value="{{ customer.id }}" />
	{% endif %}
	<input type="hidden" name="created_by" value="Tim_Noble@steris.com" />
	<div class="form-group">
		<label for="name">Name</label>
		<input type="text" class="form-control" id="name" name="name" value="{% if customer %}{{ customer.name }}{% endif %}" required />
		<div class="invalid-feedback">
			Please enter a name.
		</div>
	</div>
	<div class="form-group">
		<label for="address_one">Address 1</label>
		<input type="text" class="form-control" id="address_one" name="address_one" value="{% if customer %}{{ customer.address_one }}{% endif %}" required />
		<div class="invalid-feedback">
			Please enter an address.
		</div>
	</div>
	<div class="form-group">
		<label for="post_code">Post Code</label>
		<input type="text" class="form-control custom-validation" id="post_code" name="post_code" value="{% if customer %}{{ customer.post_code }}{% endif %}" required />
		<div class="invalid-feedback">
			Please enter a valid postcode.
		</div>
	</div>
	<div class="form-group">
		<label for="country_code">Country Code</label>
		<input type="text" class="form-control" id="country_code" name="country_code" value="{% if customer %}{{ customer.country_code }}{% endif %}" maxlength="3" required />
		<div class="invalid-feedback">
			Please enter a 3 letter country code.
		</div>
	</div>
	<div class="form-group">
		<label for="phone_number">Phone Number</label>
		<input type="text" class="form-control custom-validation" id="phone_number" name="phone_number" value="{% if customer %}{{ customer.phone_number }}{% endif %}" required />
		<div class="invalid-feedback">
			Please enter a valid phone number.
		</div>
	</div>
	<p />
	<button type="submit" class="btn btn-primary"><span class="oi oi-data-transfer-upload"></span> Submit</button>
	{% if customer %}
		<a class="btn btn-danger" role="button" href="{{ url_for('default.delete_customer', id=customer.id) }}"><span class="oi oi-delete"></span> Delete</a>
	{% endif %}
</form>
{% endblock %}
{% block custom_script %}
<script src="{{url_for('static', filename='crud-common.js')}}"></script>
<script src="{{url_for('static', filename='update-customer.js')}}"></script>
{% endblock %}